version: "3"

services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - /mnt/c/Users/6655/Documents/Project/locust:/mnt/locust
    command: -f /mnt/locust/locust.py
